# Messages
ENTER = 'ENTER'
ALLOW = 'ALLOW'
RELEASE = 'RELEASE'
HEARTBEAT = 'HEARTBEAT'
WORKING = 'WORKING'
# Process behaviors
ACTIVE = 'ACTIVE'
PASSIVE = 'PASSIVE'
BEHAVIOR_TYPES = [ACTIVE, PASSIVE]
